name = "AstroCoords"
uuid = "c7f81af5-ae1c-4d77-a3db-fd3cd0215371"
authors = ["Alexander Belotserkovtsev <abelotserkovtsev@college.harvard.edu>", "Anna Mikhailova <ann.mihaylova0306@gmail.com>"]
version = "1.0.0-DEV"

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
UnitfulExt = "Unitful"

[compat]
julia = "1.9"
Unitful = "1.20"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Test", "Unitful"]
